export enum ActionType {
	ADD_PRODUCT = 'ADD_PRODUCT',
	REMOVE_PRODUCT = 'REMOVE_PRODUCT',
	TOGGLE_ASSISTANT_MODAL = 'TOGGLE_ASSISTANT_MODAL',
	UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY',
	CLEAR_CART = 'CLEAR_CART',
	SET_ASSISTANT_MODAL_VISIBILITY = 'SET_ASSISTANT_MODAL_VISIBILITY',

	SET_TOTAL_QUANTITY = 'SET_TOTAL_QUANTITY',
}
